version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./conf:/app/conf
      - ./static:/app/static
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - SOURCE_DIR=conf
      - PREFIX=PREFIX
      - SUFFIX=SUFFIX
    command: python app.py --host=0.0.0.0 